import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, Clock3, AtSign, MapPin, Menu, Phone, Mail, Star, X } from 'lucide-react';
import { salon } from './salonData';

function BookingLink({children='Boka tid',className='button'}:{children?:React.ReactNode;className?:string}){return <a className={className} href={salon.links.booking} target="_blank" rel="noopener noreferrer">{children}<ArrowRight size={16}/></a>}
function SalonImage({src,alt,eager=false}:{src:string;alt:string;eager?:boolean}){const [status,setStatus]=useState<'loading'|'loaded'|'error'>('loading');return <div className={`image-shell ${status}`}>{status==='error'?<div className="image-fallback" role="img" aria-label={alt}><span>Hairbynimet</span><small>Bild kunde inte laddas</small></div>:null}<img src={src} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} onLoad={()=>setStatus('loaded')} onError={()=>setStatus('error')}/></div>}

function App(){
 const [menu,setMenu]=useState(false);
 const [servicePreview,setServicePreview]=useState<{src:string;alt:string}>(salon.images[1]);
 useEffect(()=>{const els=document.querySelectorAll('.reveal');const obs=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('shown')),{threshold:.12});els.forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);
 const close=()=>setMenu(false);
 const schema={'@context':'https://schema.org','@type':'HairSalon',name:salon.name,telephone:'+4645584405',email:salon.email,address:{'@type':'PostalAddress',streetAddress:salon.address.street,postalCode:salon.address.postalCode,addressLocality:salon.address.city,addressCountry:salon.address.country},sameAs:[salon.links.instagram,salon.links.booking],priceRange:'$$'};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <header className="nav"><a className="brand" href="#top" onClick={close}>HAIRBYNIMET<span>BEAUTY SALON & COMPANY</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Öppna meny">{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''} aria-label="Huvudmeny">{['Om oss','Behandlingar','Teamet','Galleri','Kontakt'].map(item=><a key={item} onClick={close} href={'#'+item.toLowerCase().replace(' ','-')}>{item}</a>)}<BookingLink/></nav></header>
 <div className="announcement" aria-label="Salongsinformation"><div><span>KLIPPNING</span><i>✦</i><span>FÄRG</span><i>✦</i><span>BALAYAGE</span><i>✦</i><span>STYLING</span><i>✦</i><span>HÅRFÖRLÄNGNING</span><i>✦</i><span>KLIPPNING</span><i>✦</i><span>FÄRG</span><i>✦</i><span>BALAYAGE</span><i>✦</i></div></div>
 <main id="top">
  <section className="hero"><div className="hero-img"><SalonImage {...salon.images[0]} eager/></div><div className="hero-copy"><p className="eyebrow">FRISÖR I HJÄRTAT AV KARLSKRONA</p><h1><span className="mask"><span>Hår med känsla.</span></span><br/><em className="mask"><span>Resultat som är du.</span></em></h1><p>Personlig hårvård, professionellt hantverk och en lugn stund mitt i stan.</p><BookingLink/><a className="discover" href="#om-oss">Upptäck salongen <ArrowDown size={15}/></a></div></section>
  <section id="om-oss" className="about-story"><div className="about-intro reveal"><p className="eyebrow">OM FÖRETAGET</p><h2>{salon.about.intro}</h2><BookingLink className="text-link">Se lediga tider</BookingLink></div><div className="about-copy reveal">{salon.about.paragraphs.map(text=><p key={text}>{text}</p>)}</div><div className="practical reveal"><p className="eyebrow">BRA ATT VETA</p><ul>{salon.about.practical.map(item=><li key={item}>{item}</li>)}</ul><div className="policy-grid"><article><span>01</span><h3>Avbokning</h3><p>{salon.about.cancellation}</p></article><article><span>02</span><h3>Betalning</h3><p>{salon.about.payment}</p></article></div><div className="upgrade"><h3>Redo för en uppgradering?</h3><p>Vi ser fram emot att ta hand om dig – och ditt hår.</p><BookingLink/></div></div></section>
  <section id="behandlingar" className="services"><div className="service-hover-preview" aria-hidden="true"><SalonImage {...servicePreview}/></div><div className="section-head reveal"><p className="eyebrow">BEHANDLINGAR & PRISER</p><h2>Hitta din behandling</h2><p>Priser och tider enligt Bokadirekt. Materialkostnad kan tillkomma för vissa färgbehandlingar.</p></div>{Object.entries(salon.services).map(([category,list],groupIndex)=><div className="service-group reveal" key={category}><h3>{category}</h3><div>{list.map((service,index)=><a href={salon.links.booking} target="_blank" rel="noopener noreferrer" className="service" key={service.name} onMouseEnter={()=>setServicePreview(salon.images[1+(groupIndex*2+index)%6])}><span><strong>{service.name}</strong><small>{service.duration}</small></span><b>{service.price}</b><ArrowRight size={18}/></a>)}</div></div>)}<div className="center reveal"><BookingLink>Visa alla behandlingar</BookingLink></div></section>
  <section id="teamet" className="team"><div className="section-head reveal"><p className="eyebrow">TEAMET</p><h2>Händerna bakom hantverket</h2></div><div className="team-grid">{salon.staff.map((person,index)=><article className="person reveal" key={person.name}><div className="person-image"><span>0{index+1}</span></div><h3>{person.name}</h3><p>{person.title}</p><BookingLink className="text-link">Boka hos {person.name.split(' ')[0]}</BookingLink></article>)}</div></section>
  <section id="galleri" className="gallery"><div className="section-head reveal"><p className="eyebrow">INSPIRATION</p><h2>Form, färg & känsla</h2><p>Ett urval av färg, klippning och styling från salongen.</p></div><div className="gallery-grid">{salon.images.slice(1).map((image,index)=><figure className={`reveal g${index}`} key={image.src}><SalonImage {...image}/></figure>)}</div></section>
  <section className="reviews reveal"><div><Star fill="currentColor"/><p className="rating">{salon.rating.value} av 5</p><p>Baserat på {salon.rating.count} verifierade betyg på {salon.rating.source}.</p></div><div className="quote"><p>Här finns plats för genuina kundomdömen när salongen har godkänt dem.</p><span>— Platshållare, inte ett kundomdöme</span></div><a className="text-link" target="_blank" rel="noopener noreferrer" href={salon.links.booking}>Se betyg på Bokadirekt <ArrowRight size={16}/></a></section>
  <section id="kontakt" className="contact"><div className="contact-card reveal"><p className="eyebrow">BESÖK OSS</p><h2>Mitt i Karlskrona</h2><a href={salon.links.map} target="_blank" rel="noopener noreferrer"><MapPin/>{salon.address.street}<br/>{salon.address.postalCode} {salon.address.city}</a><a href={salon.phoneHref}><Phone/>{salon.phoneDisplay}</a><a href={`mailto:${salon.email}`}><Mail/>{salon.email}</a><a href={salon.links.instagram} target="_blank" rel="noopener noreferrer"><AtSign/>@hairbynimet</a><div className="actions"><BookingLink/><a className="button ghost" href={salon.links.map} target="_blank" rel="noopener noreferrer">Hitta hit <ArrowRight size={16}/></a></div></div><div className="hours reveal"><Clock3/><h3>Ordinarie öppettider</h3>{salon.hours.map(([day,time])=><div key={day}><span>{day}</span><b>{time}</b></div>)}<p>Finns inte tiden du söker? Ring eller kontakta salongen via Instagram.</p></div><iframe className="map reveal" loading="lazy" title="Karta till Hairbynimet" src="https://www.google.com/maps?q=Amiralitetstorget%2025%2C%20Karlskrona&output=embed" referrerPolicy="no-referrer-when-downgrade"/></section>
 </main>
 <a className="mobile-booking" href={salon.links.booking} target="_blank" rel="noopener noreferrer">Boka tid på Bokadirekt <ArrowRight size={18}/></a>
 <footer><div className="brand">HAIRBYNIMET<span>BEAUTY SALON & COMPANY</span></div><div><b>Besök</b><p>{salon.address.street}<br/>{salon.address.postalCode} {salon.address.city}</p></div><div><b>Kontakt & länkar</b><a href={salon.phoneHref}>{salon.phoneDisplay}</a><a href={`mailto:${salon.email}`}>{salon.email}</a><a href={salon.links.booking} target="_blank" rel="noopener noreferrer">Boka tid</a><a href={salon.links.instagram} target="_blank" rel="noopener noreferrer">Instagram</a></div><div><b>Öppettider</b><p>Mån–ons 10–18<br/>Tors 10–19.30<br/>Fre 10–17</p></div><small>© {new Date().getFullYear()} {salon.name} · Privat säljdemo</small></footer></>
}
export default App;
